services:

  api:
    image: cloudpulse:api-v2.0
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  dashboard:
    image: cloudpulse:dashboard-v2.0
    build: .
    command: streamlit run dashboard/streamlit_dashboard.py --server.address=0.0.0.0
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - api