def display_metrics(metrics,average_cpu,max_cpu,total_records,min_cpu,average_memory,max_memory,min_memory,average_disk,max_disk,min_disk,logs):
    network=metrics['network_usage']
    memory=metrics['memory_usage']
    print("========================================")
    print("CloudPulse v0.4")
    print("========================================")
    print()
    print("System Information")
    print("------------------")
    print(f"Hostname: {metrics['hostname']}")
    print(f"Time:     {metrics['timestamp']}")
    print()
    print("Current Metrics")
    print("---------------")
    print(f"CPU Usage:     {metrics['cpu_usage']}%")
    print(f"Memory Usage:  {memory}%")
    print(f"Disk Usage:    {metrics['disk_usage']}%")
    print()
    print("Historical Analytics")
    print("--------------------")
    print(f"Average CPU Usage:  {average_cpu:.2f}%")
    print(f"Maximum CPU Usage:  {max_cpu:.2f}%")
    print(f"Minimum CPU Usage:  {min_cpu:.2f}%")
    print()
    print(f"Average Memory Usage:  {average_memory:.2f}%")
    print(f"Maximum Memory Usage:  {max_memory:.2f}%")
    print(f"Minimum Memory Usage:  {min_memory:.2f}%")
    print()
    print(f"Average Disk Usage: {average_disk:.2f}%")
    print(f"Maximum Disk Usage: {max_disk:.2f}%")
    print(f"Minimum Disk Usage: {min_disk:.2f}%")
    print()
    print(f"Total Records Collected: {total_records}")
    print()
    print("Network")
    print("-------")
    print(f"Bytes Sent:     {network['bytes_sent']}")
    print(f"Bytes Received: {network['bytes_recv']}")
    print()
    # print()
    # print(f"Last Updated: {metrics['timestamp']}")
    print("========================================")
    print()
    print("Logs")
    print("----")
    if not logs:
        print("No new log entries!")
    else:
        for log in logs:
            print(log)